### PR TITLE
Updated BGP AF resource module and examples

### PR DESCRIPTION
**Pull request by stalabi1**

### CODE REVIEW

**Comment by stalabi1** [comment]
@kerry-meyer @mingjunzhang2019 Requesting review

**Review by kerry-meyer — APPROVED** [review]
Thanks for re-synching the model with the corresponding module file.

Approved.

**Comment by NilashishC** [comment]
@kerry-meyer Should this be merged?

**Comment by kerry-meyer** [comment]
Nilashish: Yes. Please merge this PR.

**Pull request merged**
